mozilla-extensions/searchengine-devtools

extension/content/index.html, extension/content/script.js, extension/content/style.css, extension/experiments/searchengines/api.js, extension/experiments/searchengines/schema.json, extension/manifest.json, package.json
This adds a review where you can see which region/locales a search engine is deployed to.
I think this is probably good enough for a first version, though I'm happy to address issues if we think we need to.
=> Bug 1618575 - Add a view to searchengine-devtools where you can see which region/locales a search engine is deployed to 

extension/content/script.js, extension/experiments/searchengines/api.js, extension/manifest.json
The permissions addition to the manifest seems to get around some of the CORS request issues I've been seeing.
=> Bug 1622864 - In searchengine-devtools, always show a telemetry id, not 'undefined'.

extension/content/script.js
This is not 100% accurate as we don't have the display name, however it will likely give easier/quicker matching for most locales.
=> Bug 1628679 - Ensure engines are sorted by id within order hint.

extension/content/index.html, extension/content/script.js, extension/content/style.css, package-lock.json, package.json
This adds a new view which provides a comparison between different servers.
I've relaid out the page, as it ended up making more sense to move the tabs to the top, and re-arrange the layout.
At the moment I've broken the using the local configuration, I removed the separate button, so we probably need to rework how we're loading and caching things. I'm hoping to get those fixed soon, but I need to do other things for the next day or so, but would like to get the review process started for the work so far.
=> Bug 1628760 - Add a comparison view to show the differences between two server configurations.

extension/manifest.json, package.json, update.json
This adds an update url pointing to master for the update.json.
Also an update.json with a record in, this won't be used for the initial release that contains the update url, but contains the template for the next release.
=> Bug 1641610 - Add an update mechanism.

extension/content/index.html, extension/content/script.js, extension/content/style.css, extension/experiments/searchengines/api.js, extension/experiments/searchengines/schema.json, extension/manifest.json, package.json, update.json
This also allows fallback to the old version of the API for backwards compatibility.
=> Bug 1656532 - Extend searchengine-devtools to allow entering the experiment ID.

extension/manifest.json, package-lock.json, package.json
Adding the "mozillaAddons" permissions as required by recent add-on changes, also bumping to 1.1.8 so that we can release the recent schema updates.
=> Add mozillaAddons to permissions and bump versions for 1.1.8

extension/manifest.json, package-lock.json, package.json
In #107, I had somehow failed to properly take account of how `npm-run-all` was running the order of the scripts, and as a result, `validate.js` was only being built after the xpi was built. I probably missed testing the change properly.
Since `npm-run-all` doesn't actually add much here, and we can use pre/post build scripts to help simplify, I think we should just drop that module, and then we don't need to worry about the order of `build:*` items, as we're defining it ourselves.
=> Fix including of validate.js in the add-on, simplify the npm scripts

extension/content/script.mjs, extension/manifest.json, scripts/upload.py
Supports https://mozilla-hub.atlassian.net/browse/OPST-962 and https://mozilla-hub.atlassian.net/browse/OPST-977
=> Update Remote Settings URLs after GCP migration

schemas/search-engine-config-schema.json
This will currently cause configuration loading to fail as we have one instance where `override` isn't a boolean, but we will update the search-config before this is released.
=> Bug 1835821 - Update search-config schema with latest version.

extension/content/byEngineView.mjs, extension/content/byEngineViewOld.mjs, extension/content/configController.mjs, extension/content/enginesView.mjs, extension/content/enginesViewOld.mjs, extension/content/loader.mjs, extension/content/script.mjs, extension/experiments/searchengines/api.js, extension/experiments/searchengines/schema.json, extension/manifest.json, package-lock.json, package.json, schemas/generateValidator.js, schemas/search-config-overrides-schema.json, schemas/search-config-overrides-v2-schema.json
This adds support for the new search-config-overrides collections.
At the moment, I'm not adding options to be able to change the overrides collection - only apply what is received from the servers, or nothing if you're testing a local config.
I think this will be good enough for now, and we can add options to not apply the overrides or to be able to edit it later on.
=> fix: Add basic support for search-config-overrides(-v2).

extension/content/index.html, schemas/search-config-v2-schema.json
We've a few schema updates that we need to get into the devtools to allow it to keep working with the new schemas.
Also fixing the selection of the application name, which shouldn't allow multiple selection.
=> Update search-config-v2 schemas and stop allowing multiple selection of the application name

scripts/upload.py
I copied and pasted a section of search-config-v2 to create a new engine. When I did so, I kept the id/schema/last_modified records. The upload.py script silently failed to upload these as remote settings thought they were already there. Maybe remote settings should have complained a bit louder, but in any case, I don't think we should be attempting to set those fields.
=> chore: Fix upload script to correctly add new records, even if they re-use the same remote settings id as a different record.

extension/content/loader.mjs, extension/experiments/searchengines/api.js, extension/experiments/searchengines/schema.json
This adds search order handling to be the same as desktop. It is possible that we could move desktop's sort function to a function that we could call from the extension as well - but we would still need a fallback (at least in the short term) for the current versions of FF, and overall, I'm not sure if it is worth it as it isn't something we generally update.
=> fix: When using search-config-v2 make the order of engines behave the same as desktop (bug 1895740)

extension/content/engineUrlView.css, extension/content/engineUrlView.mjs, extension/content/enginesView.mjs, extension/content/index.html, extension/content/script.mjs, extension/content/utils.mjs, extension/experiments/searchengines/api.js, extension/experiments/searchengines/schema.json
Method and results not added in the tablet yet. We discussed adding those in another patch. 
**Light Mode:**
**Dark Mode:**
=> Add table to display engine search, suggest, and trending URLs.

extension/content/enginesView.css, extension/content/enginesView.mjs, extension/content/loader.mjs, extension/content/utils.mjs, extension/experiments/searchengines/api.js, extension/experiments/searchengines/schema.json, schemas/generateValidator.js, schemas/search-config-icons-schema.json
This adds support for 24x24 icons, filtering the icons by application version (as well as id), and validating search-config-icons according to the schema.
=> Improve icon handling and add support for display of 24x24 icons

extension/experiments/searchengines/api.js
Some records in the search configuration have no params field, this upsets the code that tries to delete the nulls, as `url.params` is null and can't be iterated over.
=> fix: Handle a URL definition not having a params field.

extension/content/engineUrlView.css, extension/content/engineUrlView.mjs, extension/content/script.mjs
This avoids clearing the table on every reload and instead updates the existing table if there is one.
=> fix: Remove flicker when selecting different engines for displaying their URLs.

extension/content/configController.mjs
I noticed that simply selecting "manual" in the latest searchengine-devtools is broken.
=> fix: Fix broken empty image configuration used for manual configurations.

extension/content/engineUrlView.css, extension/content/engineUrlView.mjs, extension/experiments/searchengines/api.js
In [bug 1916505](https://bugzilla.mozilla.org/show_bug.cgi?id=1916505) we are adding searchForm support to the search configuration. We should add the display of the search form to the list of URLs that are displayed for engines when they are clicked on.
=> Bug 1928347 - Add searchForm URL display to searchengine-devtools

extension/content/loader.mjs, extension/content/script.mjs
Changes `LOCALES_URL` to the GitHub mirror and caches the result across reloads to improve loading times.
=> Cache locales to improve loading time

extension/experiments/searchengines/api.js, extension/manifest.json, package-lock.json, package.json
With switching to the Rust based engine selector, we need to set the configuration slightly differently for searchengine-devtools.
Additionally, in preparation for the moz-src:// url protocol, I want to add fallbacks so that we can handle the before or after state
=> Fix compatibility issues

extension/experiments/searchengines/api.js, extension/experiments/searchengines/schema.json, extension/manifest.json, package.json
Records without filter expressions cause the search engine devtools to crash. This should fix it.
In the browser, its done in a similar way: https://searchfox.org/mozilla-central/rev/5bea6ede57be43d450ecc24af7a535288c9a9f7d/services/settings/remote-settings.sys.mjs#84-86
=> Fix records without a filter_expression.

extension/experiments/searchengines/api.js, extension/manifest.json, package-lock.json, package.json
Since the selector can provide the ordering, we should rely on that instead so that we can better reflect the orders that Android & iOS have.
=> fix: Stop using desktop's ordering function for search engines.
